### ISSUE TITLE
Linux port uisng unity?

### ISSUE THREAD

**Issue by SouthPenguinJay** [PiterGroot/BUASIntake#1]
I am assuming this is a unity repo.

Link to forum with links on how to do it https://www.reddit.com/r/Unity3D/comments/alanzp/what_should_i_keep_in_mind_when_porting_to_linux/

**Comment by PiterGroot** [comment]
Hello, have you actually looked at anything on this repo? This is obviously not a Unity repo, this is a game made in C++ using the SFML framework.

**Comment by SouthPenguinJay** [comment]
I'm pretty much a noob so I was only making my best guess.
Now that I know how it is made I'll be able to look into it a bit more. Was looking for random c++ projects for practice

**Comment by PiterGroot** [comment]
Ah ok I understand, if you have some specific questions about this repo, i'll try to answer them.
